preface + introduction
nemtech/catapult-whitepaper pull request #1
Opened 2019-11-12 18:10 UTC by Jaguar0625

2019-11-13 09:49 UTC, gimer commented on whitepaper/chapters/introduction.tex
> +Currently, the following hash algorithms are supported:
how to refer to sha and/or keccak with things like secret lock?

2019-11-13 09:51 UTC, gimre-xymcity approved these changes

2019-11-13 11:41 UTC, BloodyRookie requested changes

2019-11-13 11:41 UTC, BloodyRookie commented on whitepaper/chapters/introduction.tex
> +Any node can download complete copy of the chain and can independently verify it at all times.
download *a/the* complete

2019-11-13 11:41 UTC, BloodyRookie commented on whitepaper/chapters/introduction.tex
> +These choices neccesarily sacrifice some throughput relative to other protocols, but they seem most consistent with the philosophical underpinnings of Bitcoin.
necessarily

2019-11-13 11:41 UTC, BloodyRookie commented on whitepaper/chapters/introduction.tex
> +As part of a focus on trustlessnes, the following features were added relative to NEM:
trustlessness

2019-11-13 11:41 UTC, BloodyRookie commented on whitepaper/chapters/introduction.tex
> -\nemchapterfirstletter{N}{EM}, in its most basic form, is a crypto currency that is built on block chain technology.
block chain or blockchain, we should be consistent

2019-11-13 11:41 UTC, BloodyRookie commented on whitepaper/chapters/introduction.tex
> +Allowing the composition of nodes to vary dynamically based on real needs, should lead to a more globally resource-optimized network.
is , correct?

2019-11-13 11:41 UTC, BloodyRookie commented on whitepaper/chapters/introduction.tex
> +Basing the core block and transaction pipelines on the disruptor pattern - and using parallel processing wherever processing - allows high rates of transactions per second relative to a typical block
`parallel processing wherever processing` => `parallel processing whenever possible`?
(processing is not always parallel)

2019-11-13 11:41 UTC, BloodyRookie commented on whitepaper/chapters/introduction.tex
> +NIS1 was a worthy entry into the blockchain landscape and \codenamespace is an even worthier evolution of it.
what is the difference between \codename and \codenamespace? Both seems to be resolved to `Catapult`

2019-11-13 11:41 UTC, BloodyRookie commented on whitepaper/preface.tex
> +In this, we think we succeded.
think, we ?

2019-11-14 05:47 UTC, dgarcia360 commented on whitepaper/chapters/introduction.tex
> +\item api: These nodes store data in a mongo database for easier querying and can be used in combination with a NodeJS REST server.
Replace mongo database -> MongoDB document database

2019-11-14 16:17 UTC, merged