System comments
nemtech/catapult-whitepaper pull request #21
Opened 2020-01-17 19:44 UTC by dgarcia360

Added a reference and fixed a typographical convention. 

Other comments not solved in this PR:

- [ ] Handlers: These are APIs that are always accessible. -> By whom? You could also add an example of a handler.
- [ ] Diagnostics: I don't understand the meaning of the word ``counters`` in that context.
- [ ] Broker: "It’s expected that the server and broker have different extensions loaded."→ Why brokers and servers of the same network are expected to have different extensions loaded?

2020-01-17 23:00 UTC, Jaguar0625 commented
> Handlers: These are APIs that are always accessible. -> By whom? You could also add an example of a handler.

All clients. There is no filter.

>  Diagnostics: I don't understand the meaning of the word counters in that context.

think of it like a win32 performance counter. for example, we have counters like:
```
   ACCTREST C : 0     |      ACNTST C : 33    |  ACNTST C HVA : 9     |  ACTIVE PINGS : 0     | 
    B WRITERS : 0     |       BAN ACT : 0     |       BAN ALL : 0     |  BLK ELEM ACT : 0     | 
 BLK ELEM TOT : 182   |      BLKDIF C : 41    |        HASH C : 39    |    HASHLOCK C : 0     | 
  MEM CUR RSS : 85    |  MEM CUR VIRT : 4'758 |   MEM MAX RSS : 87    |   MEM SHR RSS : 37    | 
   METADATA C : 0     |      MOSAIC C : 2     |  MOSAICREST C : 0     |    MULTISIG C : 0     | 
        NODES : 8     |          NS C : 1     |       NS C AS : 3     |       NS C DS : 3     | 
RB COMMIT ALL : 2     | RB COMMIT RCT : 1     | RB IGNORE ALL : 4     | RB IGNORE RCT : 4     | 
      READERS : 8     |  SECRETLOCK C : 0     | SUCCESS PINGS : 32    |         TASKS : 13    | 
TOT CONF TXES : 39    |   TOTAL PINGS : 32    |   TS NODE AGE : 2     | TS OFFSET ABS : 0     | 
TS OFFSET DIR : 0     |  TS TOTAL REQ : 8     |   TX ELEM ACT : 0     |   TX ELEM TOT : 0     | 
 UNLKED ACCTS : 1     |      UT CACHE : 0     |       WRITERS : 5     |  
```

>  Broker: "It’s expected that the server and broker have different extensions loaded."→ Why brokers and servers of the same network are expected to have different extensions loaded?

Consider peer, api and dual server. They will all have different extensions loaded.
Additionally, some api/dual nodes might want to support zmq but not mongo or vice versa.

2020-01-21 13:17 UTC, dgarcia360 commented
@Jaguar0625 Thanks for the explanations! I just submitted some new suggestions.

2020-01-22 13:31 UTC, Jaguar0625 requested changes

2020-01-22 13:31 UTC, Jaguar0625 commented on whitepaper/chapters/system.tex
> +		Specify new transaction types and the mapping of those types to parsing rules.
Specify or Define ?

2020-01-22 13:31 UTC, Jaguar0625 commented on whitepaper/chapters/system.tex
> +			The registered validators can subscribe to general or plugin-defined notifications and reject disallowed values or state changes.
extra indent

2020-01-22 13:31 UTC, Jaguar0625 commented on whitepaper/chapters/system.tex
> +\nemrefparens{sec:accounts:addressaliases}.
indent or move to prev line

2020-01-22 13:31 UTC, Jaguar0625 commented on whitepaper/chapters/system.tex
> +To illustrate, the server might want to support harvesting capabilities, but the broker does not normally load this extension.
~capabilities~ ? (not sure)

2020-01-22 13:54 UTC, dgarcia360 commented
@Jaguar0625 Do not merge this one yet. I'll review the consistency with bullets points from other sections (if they start with verb or noun).

2020-01-27 14:36 UTC, dgarcia360 commented
If we want to apply those changes we would need to read every other bullet point. Closing this by now, if necessary will open a new PR.

2020-01-27 14:36 UTC, closed without merging